---

plugins:
  - import

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:import/recommended'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  linebreak-style: 0
