---

plugins:
  - import

env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:import/recommended'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
